version: "3.1"

networks:
  public-network:

  private-network:
    internal: true

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - recipe-service
    networks:
    - public-network
    - private-network
    ports:
    - "8080:8080"

  recipe-service:
    image: getdrop/recipe:0.0.1-SNAPSHOT
    restart: always
    container_name: recipe-service
    depends_on:
    - mongodb
    networks:
    - private-network
    ports:
    - "8080:8080"

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
     - "27017:27017"
    networks:
    - private-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: recipe-db
    volumes:
      - ./mongo-init.js/:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #  - ./database:/data/db # for making data available out of container

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    networks:
    - public-network
    - private-network
    depends_on:
    - mongodb
    ports:
    - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
