version: "3.1"

networks:
  public-network:

  private-network:
    internal: true

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
    - private-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    networks:
    - public-network
    - private-network
    depends_on:
    - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
