version: "3.1"

networks:
  public-network:

  private-network:
    internal: true

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    networks:
    - private-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    #volumes:
    #  - ./database:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express
    networks:
    - public-network
    - private-network
    depends_on:
    - mongodb
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
